services:
  db:
    image: postgres:16
    container_name: db_container
    restart: always
    env_file: ./credentials.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - fraud_network

  spark-master:
    image: bitnami/spark:3.5
    container_name: spark_master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
    ports: # Web UI and master port respectively
      - "8080:8080"
      - "7077:7077"
    networks:
      - fraud_network

  spark-worker:
    image: bitnami/spark:3.5
    container_name: spark_worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
    depends_on:
      - spark-master
    networks:
      - fraud_network

networks:
  fraud_network:
    driver: bridge

volumes:
  postgres_data: